feat: full application layout
asyncapi/simulator pull request #114
Opened 2022-04-12 10:55 UTC by NektariosFifes

**Description**

- Titlebar
- Sidebar
- Text editor
- container for visualization not functionality just visual

**Related issue(s)**

2022-04-20 13:00 UTC, NektariosFifes commented
@jonaslagoni should i split it in a smaller commit?

2022-04-22 09:07 UTC, jonaslagoni requested changes
Going forward don't put everything in one PR, I would rather have 100 small PRs than one large 😄 There is no way I can help you out properly as there are too many changes to keep track of. Up to you if you want to split it up.

You have a lot of disabled eslint lines. They are there for a reason, among other reasons to create consistency. Some of them can be a bit of a pain, and in some cases, they might not be needed, but I can't seem to figure out why all of them are needed here? 

Each time you need to disable something, try and second guess why you need to disable them. You can always suggest changing the eslint config, but remember to have your arguments in order why a consistency is not needed, etc 😄

2022-04-22 09:07 UTC, jonaslagoni commented on Desktop/src/renderer/containers/Workbench/components/test.js
> +getArrayMetadata();
Why is this file here?

2022-04-22 09:07 UTC, jonaslagoni commented on Desktop/src/renderer/containers/Workbench/components/test.d.ts
> +export function getArrayMetadata(arr: any[]): ArrayMetadata;
Why is this file here?

2022-04-25 13:11 UTC, NektariosFifes commented on Desktop/src/renderer/containers/Workbench/components/test.d.ts
> +export function getArrayMetadata(arr: any[]): ArrayMetadata;
removed it

2022-04-25 13:15 UTC, NektariosFifes commented
i will remove eslints

2022-04-27 23:23 UTC, jonaslagoni approved these changes

2022-04-28 04:50 UTC, merged