feat: Added the basic UI for Simulator Desktop Application.
asyncapi/simulator pull request #185
Opened 2023-08-19 04:59 UTC by SumantxD

Fixes #179 after the revert

2023-08-22 15:23 UTC, NektariosFifes commented
hey @SumantxD sorry for not informing you but i did not revert eventually. i just  made a commit with the feat: prefix.

2023-09-01 20:33 UTC, SumantxD commented
@NektariosFifes I have added the feature to add nodes with the help of a menu and drag and drop

2023-09-17 19:08 UTC, NektariosFifes commented
awesome work man

2023-09-17 19:33 UTC, NektariosFifes commented
@SumantxD can you add a description and make a list about what this commit adds. this will be useful for tracking progress and also very useful for your potential future employers when they will be reviewing your commit history in your cv.

2023-09-18 16:51 UTC, SumantxD commented
> @SumantxD can you add a description and make a list about what this commit adds. this will be useful for tracking progress in the project and also very useful for your potential future employers when they will be reviewing your commit history in your cv.
> 
> Also the title is a bit general with not specify you have added node addition and manipulation options

Done !! :tada:

2023-09-20 22:40 UTC, NektariosFifes requested changes

2023-09-20 22:40 UTC, NektariosFifes commented on Desktop/src/renderer/AddNodesDnD/AddButton.tsx
> +            <a href="#" className="menu-item" onClick={() => props.goToMenu && setActiveMenu(props.goToMenu)}>
When the menu item components are dragged in the canvas the application throws an unhandled exception. You should make the menu-item class items not be draggable at all.

2023-09-21 17:54 UTC, NektariosFifes commented on Desktop/src/renderer/AddNodesDnD/AddButton.tsx
> +            <a href="#" className="menu-item" onClick={() => props.goToMenu && setActiveMenu(props.goToMenu)}>
try dragging into the canvas the add nodes option in the menu it will crash the application

2023-09-22 07:07 UTC, SumantxD commented on Desktop/src/renderer/AddNodesDnD/NodeInput/Application.tsx
> +import "./index.css"; // Import the custom CSS file
Done !! :tada:

2023-09-22 07:07 UTC, SumantxD commented on Desktop/src/renderer/containers/Workbench/index.tsx
> +import React, { useEffect, useState } from 'react';
Done !! :tada:

2023-09-22 07:08 UTC, SumantxD commented on Desktop/src/renderer/GraphGenerator/ApiVisualizer.tsx
>        //so we have been successfully be able to generate the newNodes and newEdges
Done !! :tada:

2023-09-22 07:11 UTC, SumantxD commented on Desktop/src/renderer/GraphGenerator/ApiVisualizer.tsx
>        //new entities....
Done !! :tada:

2023-09-22 07:12 UTC, SumantxD commented on Desktop/src/renderer/GraphGenerator/ApiVisualizer.tsx
Done !! , i have moved it under parser/utils/layout

2023-09-22 07:13 UTC, SumantxD commented on Desktop/src/renderer/GraphGenerator/ApiVisualizer.tsx
>  interface AutoLayoutProps { }
Done !! :tada:

2023-09-27 05:47 UTC, NektariosFifes requested changes

2023-10-14 06:39 UTC, SumantxD commented on Desktop/src/renderer/GraphGenerator/ApiVisualizer.tsx
> +          <ReactFlowProvider>
Yes the wrapper is not needed, actually i forgot to remote it form a previous implementation where i was trying to add the DragAndDrop menu but later i figured out that the DragAndDrop menu can have access to canvas elements by by using the <Panel/> element provided by React-Flow

2023-11-15 09:38 UTC, NektariosFifes commented
@SumantxD hey check the sonar cloud analysis there is some code duplication

2023-12-11 03:27 UTC, NektariosFifes approved these changes

2023-12-11 03:29 UTC, merged